package com.example.movieapp.utils

object Constants {
    const val SHARED_PREFERENCES_KEY = "movie_app_shared_prefs"
    const val SHARED_PREFERENCES_USERNAME = "user_name"
    const val SHARED_PREFERENCES_LAST_CONNECTION = "last_date_logged_in"
    const val SHARED_PREFERENCES_IS_USER_LOGGED = "is_user_logged_in"
    const val MOVIE_ITEM_TYPE = "movie"
    const val LOGOUT = "Logout"
    const val USER_IS = "user"
    const val USER_IS_TEXT = "User: "
    const val PASSWORD_IS = "1234"
    const val USER_TEXT = "User"
    const val PASSWORD_TEXT = "Password"
    const val DATE_FORMAT = "yyyy:MM:dd HH:mm:ss"
    const val LOG_IN = "Log in"
    const val USER_OR_PASSWORD_INCORRECT_TEXT = "User or Password are incorrect"
    const val NO_FAVORITES_SAVED = "No Favorites Saved"
    const val MOVIE_TEXT = "Movie"
    const val YEAR_TEXT = "Year"
    const val TYPE_TEXT = "Type"
    const val LOGIN_TITLE = "Login"
    const val SEARCH_TITLE = "Search"
    const val FAVORITES_TITLE = "Favorites"
    const val LOGIN_ROUTE = "login"
    const val SEARCH_ROUTE = "search"
    const val FAVORITES_ROUTE = "favorites"
    const val APP_NAME = "MOVIE APP"
}
